# 1. Base stage: shared environment
FROM node:20.18-alpine AS base
ENV NEXT_TELEMETRY_DISABLED 1
WORKDIR /app

# 2. Dependencies stage: install only what's needed for build
FROM base AS deps
# Install libc6-compat for some native node modules support
RUN apk add --no-cache libc6-compat

# Install dependencies based on the package-lock.json
COPY package.json package-lock.json* ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

# 3. Builder stage: build the application
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Run build leveraging Next.js build cache
RUN --mount=type=cache,target=/app/.next/cache \
    npm run build

# 4. Runner stage: final lean production image
FROM base AS runner
RUN apk add --no-cache curl
ENV NODE_ENV production

# Create nextjs user for better security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy essential standalone artifacts
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Set permissions for prerender cache
RUN mkdir -p .next && chown nextjs:nodejs .next

USER nextjs

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Healthcheck to monitor app status
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:3000/api/health || exit 1

# Start the application using server.js generated by standalone build
CMD ["node", "server.js"]
